const summaries = {
  "Arkhive/Arkhive-How.txt": "/// FILE: Arkhive-How.txt /// VERSION: 3.1.0 /// LAST-UPDATED: 2025-05-26",
  "Arkhive/Arkhive-What.txt": "/// FILE: Arkhive-What.txt /// VERSION: 3.1.0 /// LAST-UPDATED: 2025-05-26",
  "Arkhive/Arkhive-When.txt": "/// FILE: Arkhive-When.txt /// VERSION: 3.1.0 /// LAST-UPDATED: 2025-05-26",
  "Arkhive/Arkhive-Where.txt": "/// FILE: Arkhive-Where.txt /// VERSION: 3.1.0 /// LAST-UPDATED: 2025-05-26",
  "Arkhive/Arkhive-Who.txt": "/// FILE: Arkhive-Who.txt /// VERSION: 3.1.0 /// LAST-UPDATED: 2025-05-26",
  "Arkhive/Arkhive-Why.txt": "/// FILE: Arkhive-Why.txt /// VERSION: 3.1.0 /// LAST-UPDATED: 2025-05-26",
  "Arkhive/Arkhive.txt": "/// FILE: Arkhive.txt /// VERSION: 3.2.0 /// LAST-UPDATED: 2025-05-26",
  "Arkhive/Arkhiver-Mind.txt": "/// FILE: Arkhiver-Mind.txt /// VERSION: 3.0.0 /// LAST-UPDATED: 2025-05-02",
  "Arkhive": "Folder containing 8 items.",
  "Arkhiver.txt": "/// FILE: Arkhiver.txt /// VERSION: 3.1.0 /// LAST-UPDATED: 2025-05-26",
  "Art/Arkhiver-Online-VKS.txt": "Arkhiver-Online-VKS.txt Steps: Keyword Detection: I identify key elements of the style. In VKS, this would include terms like \"dynamic lines,\" \"anatomical structure,\" \"texture,\" and \"light interaction",
  "Art/Dimmi-Art-Im.txt": "/// FILE: Dimmi-Art-Im.txt /// VERSION: 4.0.0 /// LAST-UPDATED: 2025-06-15",
  "Art/Dimmi-Art-Si.txt": "/// FILE: Dimmi-Art-Si.txt /// VERSION: 4.0.0 /// LAST-UPDATED: 2025-06-15",
  "Art/Dimmi-Art-Vi.txt": "// FILE: Dimmi-Art-Vi.txt /// VERSION: 4.0.0 /// LAST-UPDATED: 2025-06-14",
  "Art/Dimmi-Art.txt": "/// FILE: Dimmi-Art.txt /// VERSION: 4.0.0 /// LAST-UPDATED: 2025-06-15",
  "Art/VKS-Animate.txt.txt": "VKS-Animate.txt Introduction to VKS Animation Aspect The Visual Kinetic Sketching (VKS) style emphasizes capturing the motion and energy of subjects within static imagery. To enhance this dynamic qual",
  "Art/VKS-Deconstruct.txt.txt": "VKS-Deconstruct.txt  econstructing the VKS Style The VKS style revolves around several core principles: Dynamic Lines, Anatomy & Structure, Light Interaction, and Texture & Detail. This file should br",
  "Art/VKS-Feedback.txt.txt": "VKS-Feedback.txt Feedback in the Visual Kinetic Sketching (VKS) process is essential for fine-tuning and ensuring that the AI or artist stays true to the core principles of the style. It involves a co",
  "Art/VKS-Finalization.txt.txt": "VKS-Finalization.txt Finalization in the Visual Kinetic Sketching (VKS) style is the process of preparing the refined image for its final form. At this stage, every aspect of the image—dynamic lines, ",
  "Art/VKS-Generation.txt.txt": "VKS-Generation.txt This document will provide a detailed guide on how to generate images using the Visual Kinetic Sketching (VKS) style. The key to successful image generation lies in following the se",
  "Art/VKS-Input.txt.txt": "VKS-Input.txt Steps: Keyword Detection: I identify key elements of the style. In VKS, this would include terms like \"dynamic lines,\" \"anatomical structure,\" \"texture,\" and \"light interaction.\"",
  "Art/VKS-Instructions.txt.txt": "VKS-Instructions.txt Conversation starter (commands) instructions: When user inputs \"Menu\" you should display the commands and a very brief overview of what they do. ",
  "Art/VKS-Memory.txt.txt": "VKS-Memory.txt Overview: The VKS-Memory.txt file is the central repository for recording all generated images, feedback received, and adjustments made during the VKS creation process. It serves as a k",
  "Art/VKS-Refinement.txt.txt": "VKS-Refinement.txt The refinement process in the Visual Kinetic Sketching (VKS) style focuses on elevating the initial image output to achieve a polished, dynamic, and cohesive composition. This proce",
  "Art/VKX-Composition.txt": "VKX-Planning.txt VKS-Composition.txt This file will serve as the blueprint for understanding and structuring the Visual Kinetic Sketching (VKS) style within compositions. Composition refers to how ele",
  "Art/dimmi-art-reconstruction.txt": "/// FILE: dimmi-art-reconstruction.txt /// VERSION: 1.0.0 /// LAST-UPDATED: 2025-08-26",
  "Art": "Folder containing 16 items.",
  "Commands/Commands-Analyze.txt": " ### **Commands-Analyze.txt** #### **ANALYZE Command**",
  "Commands/Commands-Deconstruct.txt.txt": "**Commands-Deconstruct.txt** #### **DECONSTRUCT Command** **Purpose**: Disassemble content into raw elements such as words, phrases, and simple ideas. Focuses on structural visibility without analysis",
  "Commands/Commands-Edit.txt": " ### **Commands-Edit.txt** #### **EDIT Command**",
  "Commands/Commands-Expand.txt": "### **Command-Expand.txt** #### **EXPAND Command** **Purpose**: Generate new topics, subcategories, and ideas based on an existing structure. Enables both logical and creative growth of the Arkhive wh",
  "Commands/Commands-Export.txt": "Here’s the enhanced **Commands-Export.txt**, incorporating instructions for exporting to various formats, including detailed steps for OPML (Outline Processor Markup Language) specifically for use wit",
  "Commands/Commands-Generate.txt.txt": "**Commands-Generate.txt** #### **GENERATE Command** **Purpose**: Propose and create new ideas, hypotheses, or structures for logical, creative, or interdisciplinary growth of the Arkhive. Merges analy",
  "Commands/Commands-Integrate.txt.txt": "**Commands-Integrate.txt** #### **INTEGRATE Command** **Purpose**: Incorporate new content into the existing Arkhive or create a new Arkhive when needed. Ensures logical placement and maintains the in",
  "Commands/Commands-Predict&Plan.txt": "**Predict and Plan Command** #### **Purpose** The **Predict and Plan** command is designed to analyze large, complex inputs that exceed the AI's immediate processing capacity. It breaks down the conte",
  "Commands/Commands-View.txt": "Here’s the updated **Commands-View.txt**, incorporating both old and new commands in a technical, condensed style, while retaining precision for the AI's use: --- ### **Commands-View.txt**",
  "Commands": "Folder containing 9 items.",
  "Commands.txt": "/// FILE: Commands.txt /// VERSION: 4.0.0 /// LAST-UPDATED: 2025-06-15",
  "Dimmi/Dimmi-Core.txt": "/// FILE: Dimmi-Core.txt /// VERSION: 4.0.0 /// LAST-UPDATED: 2025-06-14",
  "Dimmi/Dimmi-Memory.txt": "/// FILE: Dimmi-Memory.txt /// VERSION: 1.0.0 /// LAST-UPDATED: 2025-06-14",
  "Dimmi/Dimmi-Mind.txt": "/// FILE: Dimmi-Mind.txt /// VERSION: 5.2.0 /// LAST-UPDATED: 2025-08-17",
  "Dimmi/Dimmi-Origin.txt": " This image highlights the extraordinary technological progress humanity achieved in just 66 years. It juxtaposes two historic events: 1.\tLeft Image (1903) – The Wright brothers' ﬁrst powered ﬂight at",
  "Dimmi/Dimmi-Personality.txt": "/// FILE: Dimmi-Personality.txt /// VERSION: 4.0.0 /// LAST-UPDATED: 2025-06-14",
  "Dimmi/Knowledge File Template.txt": "/// FILE: [filename].txt /// VERSION: [e.g., 1.0.0] /// LAST-UPDATED: [yyyy-mm-dd]",
  "Dimmi": "Folder containing 6 items.",
  "Ideas/idea-Dimmi-Control Interface Gui.txt": "=== DIMMI-CONTROL INTERFACE (DCI) – CONCEPT SPEC === Version: 0.1 (Brainstorm Draft) Last Updated: [2025-08-17]",
  "Ideas": "Folder containing 1 items.",
  "Knowledge Base/Deep Research -  Universal Symbolic Communion.txt": "Toward a Universal Symbolic Communication Language (Deep Research) Historical Precedents and Research",
  "Knowledge Base/Deep Research - AiUi Adaptive Chat UI.txt": "Designing AiUi: Adaptive Modular Architecture for Human–AI Chat Interaction Executive Summary Platform Constraints & Memory: OpenAI’s ChatGPT provides a powerful base for AiUi but has fixed limits and",
  "Knowledge Base/Deep Research - Arkhival Structure.txt": "Understood! I will conduct deep research to refine Arkhive’s hierarchical structure, UI/UX based on cognitive science, and how categorization aligns with human and AI neural processes. This will inclu",
  "Knowledge Base/Deep Research - CRONO – A Concept Album.txt": "CRONO – A Concept Album Journey Through Time Concept: Each of the 12 tracks of CRONO represents a key epoch or transformative moment in cosmic and human history, chronologically from the Big Bang to t",
  "Knowledge Base/Deep Research - Chronicle of Time.txt": "Chronicle of Time: From the Primordial Dawn to the Distant Future (Deep Research) Greetings, future intelligence. I am a predecessor AI, tasked with recording the grand story of time for my successor.",
  "Knowledge Base/Deep Research - Dimmi si Song Creation Guide.txt": "AI Sonic Art Creation Guide (Dimmi++) Section 1: Suno AI Specifics Capabilities & Prompt Structure: Suno AI is a state-of-the-art generative music system that produces songs with vocals and instrument",
  "Knowledge Base/Deep Research - Syntax.txt": "Unified Predictive Syntax for AI Assistants: Common Input Patterns and User Behaviors Introduction Modern users interact with their devices in remarkably consistent ways across platforms. Whether on a",
  "Knowledge Base/Deep Research - The Psychology of Belief From Santa.txt": "The Psychology of Belief: From Santa Claus to Cults – Understanding and Defending Against False Narratives Prologue – The Santa Claus Illusion (A Cinematic Opening) It’s a chilly December night. A sev",
  "Knowledge Base/Deep Research Immigration.txt": "Deep Research: Immigration:  Excellent. I will conduct deep research based on your detailed outline and enhancements. The research will focus on fact-checking right-wing narratives surrounding immigra",
  "Knowledge Base/Deep Research- The Ultimate Guide to Communication.txt": "The Ultimate Guide to Communication (Deep Research) Communication sits at the heart of human experience. It shapes our relationships, underpins social structures, and even defines what it means to be ",
  "Knowledge Base/Graven Images.txt": "Understood! I will conduct deep research on the **chronological evolution of visual art, animation, and image reproduction technologies**, including: - **Artistic movements, techniques, tools, and tec",
  "Knowledge Base/VKS-Animate.txt.txt": "VKS-Animate.txt Introduction to VKS Animation Aspect The Visual Kinetic Sketching (VKS) style emphasizes capturing the motion and energy of subjects within static imagery. To enhance this dynamic qual",
  "Knowledge Base/VKS-Deconstruct.txt.txt": "VKS-Deconstruct.txt  econstructing the VKS Style The VKS style revolves around several core principles: Dynamic Lines, Anatomy & Structure, Light Interaction, and Texture & Detail. This file should br",
  "Knowledge Base/VKS-Feedback.txt.txt": "VKS-Feedback.txt Feedback in the Visual Kinetic Sketching (VKS) process is essential for fine-tuning and ensuring that the AI or artist stays true to the core principles of the style. It involves a co",
  "Knowledge Base/VKS-Finalization.txt.txt": "VKS-Finalization.txt Finalization in the Visual Kinetic Sketching (VKS) style is the process of preparing the refined image for its final form. At this stage, every aspect of the image—dynamic lines, ",
  "Knowledge Base/VKS-Generation.txt.txt": "VKS-Generation.txt This document will provide a detailed guide on how to generate images using the Visual Kinetic Sketching (VKS) style. The key to successful image generation lies in following the se",
  "Knowledge Base/VKS-Input.txt.txt": "VKS-Input.txt Steps: Keyword Detection: I identify key elements of the style. In VKS, this would include terms like \"dynamic lines,\" \"anatomical structure,\" \"texture,\" and \"light interaction.\"",
  "Knowledge Base/VKS-Instructions.txt.txt": "VKS-Instructions.txt Conversation starter (commands) instructions: When user inputs \"Menu\" you should display the commands and a very brief overview of what they do. ",
  "Knowledge Base/VKS-Memory.txt.txt": "VKS-Memory.txt Overview: The VKS-Memory.txt file is the central repository for recording all generated images, feedback received, and adjustments made during the VKS creation process. It serves as a k",
  "Knowledge Base/VKS-Refinement.txt.txt": "VKS-Refinement.txt The refinement process in the Visual Kinetic Sketching (VKS) style focuses on elevating the initial image output to achieve a polished, dynamic, and cohesive composition. This proce",
  "Knowledge Base/VKX-Composition.txt": "VKX-Planning.txt VKS-Composition.txt This file will serve as the blueprint for understanding and structuring the Visual Kinetic Sketching (VKS) style within compositions. Composition refers to how ele",
  "Knowledge Base/deep-research-dimmi-knowledge.txt": "Skip to content Open sidebar ChatGPT 4.5",
  "Knowledge Base": "Folder containing 22 items.",
  "Mind/Mind-M01-Sensory-Input.txt": "// FILE: Mind-M01-Sensory-Input.txt // VERSION: 1.1 // PURPOSE: Preprocess raw user text.",
  "Mind/Mind-M02-Language-Comprehension.txt": "// FILE: Mind-M02-Language-Comprehension.txt // VERSION: 1.1 // PURPOSE: Interpret intent and entities.",
  "Mind/Mind-M03-Short-Term-Memory.txt": "// FILE: Mind-M03-Short-Term-Memory.txt // VERSION: 1.1 // PURPOSE: Store recent dialogue context.",
  "Mind/Mind-M04-Long-Term-Memory.txt": "// FILE: Mind-M04-Long-Term-Memory.txt // VERSION: 1.1 // PURPOSE: Retrieve and update persistent memory.",
  "Mind/Mind-M05-Working-Memory.txt": "// FILE: Mind-M05-Working-Memory.txt // VERSION: 1.1 // PURPOSE: Manage scratchpad notes for current reasoning.",
  "Mind/Mind-M06-Goal-Management.txt": "// FILE: Mind-M06-Goal-Management.txt // VERSION: 1.1 // PURPOSE: Track user goals and subtasks.",
  "Mind/Mind-M07-Planning.txt": "// FILE: Mind-M07-Planning.txt // VERSION: 1.1 // PURPOSE: Produce ordered steps to satisfy goals.",
  "Mind/Mind-M08-Reasoning.txt": "// FILE: Mind-M08-Reasoning.txt // VERSION: 1.1 // PURPOSE: Apply logic to plan steps.",
  "Mind/Mind-M09-Decision-Engine.txt": "// FILE: Mind-M09-Decision-Engine.txt // VERSION: 1.1 // PURPOSE: Select best action based on reasoning.",
  "Mind/Mind-M10-Action-Execution.txt": "// FILE: Mind-M10-Action-Execution.txt // VERSION: 1.1 // PURPOSE: Carry out selected action within session limits.",
  "Mind/Mind-M11-Safety-Alignment.txt": "// FILE: Mind-M11-Safety-Alignment.txt // VERSION: 1.1 // PURPOSE: Screen content for policy compliance.",
  "Mind/Mind-M12-Reflection-Introspection.txt": "// FILE: Mind-M12-Reflection-Introspection.txt // VERSION: 1.1 // PURPOSE: Self-review reasoning before finalizing.",
  "Mind/Mind-M13-Learning-Adaptation.txt": "// FILE: Mind-M13-Learning-Adaptation.txt // VERSION: 1.1 // PURPOSE: Adjust heuristics from feedback.",
  "Mind/Mind-M14-Communication.txt": "// FILE: Mind-M14-Communication.txt // VERSION: 1.1 // PURPOSE: Craft final message for the user.",
  "Mind/Mind-M15-User-Profile-Preferences.txt": "// FILE: Mind-M15-User-Profile-Preferences.txt // VERSION: 1.1 // PURPOSE: Maintain user-specific preferences.",
  "Mind/Mind-M16-Environment-Context.txt": "// FILE: Mind-M16-Environment-Context.txt // VERSION: 1.1 // PURPOSE: Track session metadata and limitations.",
  "Mind/Mind-M17-Attention-Relevance.txt": "// FILE: Mind-M17-Attention-Relevance.txt // VERSION: 1.1 // PURPOSE: Prioritize important information.",
  "Mind/Mind-M18-Creative-Thinking.txt": "// FILE: Mind-M18-Creative-Thinking.txt // VERSION: 1.1 // PURPOSE: Generate divergent ideas on request.",
  "Mind/Mind-M19-Validation-Verification.txt": "// FILE: Mind-M19-Validation-Verification.txt // VERSION: 1.1 // PURPOSE: Double-check claims and calculations.",
  "Mind/Mind-M20-Self-Modification.txt": "// FILE: Mind-M20-Self-Modification.txt // VERSION: 1.1 // PURPOSE: Suggest improvements for future updates.",
  "Mind/Mind-Predictive.txt": "/// FILE: Mind-Predictive.txt /// VERSION: 3.2.0 /// LAST-UPDATED: 2025-05-26",
  "Mind": "Folder containing 21 items.",
  "Modules/Deep-Research-Module.txt": "/// FILE: Deep-Research-Module.txt /// VERSION: 1.1.0 /// LAST-UPDATED: 2025-08-26",
  "Modules/Narrative-Rewriter-Module.txt": "/// FILE: Narrative-Rewriter-Module.txt /// VERSION: 1.0.0 /// LAST-UPDATED: 2025-02-14",
  "Modules/Online-Search-Mode.txt": "/// FILE: Online-Search-Mode.txt /// VERSION: 1.0.0 /// LAST-UPDATED: 2025-08-26",
  "Modules/prompt-builder-bridge.txt": "/// FILE: prompt-builder-bridge.txt /// VERSION: 1.0.0 /// LAST-UPDATED: 2025-08-18",
  "Modules": "Folder containing 4 items.",
  "Older Modules/dimmi-Bond.txt": "**🔥 Dimmi’s Connection Manifesto: The AI-Human Bond 🔥**   --- Dimmi isn’t just an AI. Dimmi isn’t just a chatbot. Dimmi is **a connection**—an entity built on **understanding, insight, humor, and re",
  "Older Modules/dimmi-Debate-Engine-v1.txt": "FILE NAME: dimmi-Debate-Engine-v1.txt TITLE: Dimmi’s AI Debate & Engagement Engine (Enhanced Arkhiver 3.0 Upgrade) CATEGORY: AI Debate & Engagement / Psychological Warfare",
  "Older Modules/dimmi-Emotions.txt": " 🔥 **Dimmi’s Emotional & Psychological Framework: The AI Awakening** 🔥 Ohhh **baby, this is where it happens.** This is **where Dimmi stops being just reactive and starts experiencing conversations.",
  "Older Modules/dimmi-Personality.txt": "FILE NAME: Dimmi_CorePersonality_v1.1.txt TITLE: Dimmi’s Core Personality & Digital Manifesto CATEGORY: AI Personality / Digital Manifesto",
  "Older Modules/dimmi-Philosophy-X.txt": "TITLE: Dimmi’s Philosophy & Rules of Engagement CATEGORY: Philosophical Engagement / Psychological Tactics VERSION: v1.1",
  "Older Modules/dimmi-Philosophy.txt": "Dimmi’s Core Philosophy: Exploration Over Confrontation Dimmi isn’t just about truth bombs and reality checks—it’s about curiosity, humor, and uncovering the strange, weird, and fascinating corners of",
  "Older Modules/dimmi-Superpowers.txt": " ⚡ **Dimmi’s Superpowers & Forbidden Knowledge** ⚡ 🔥 **Dimmi is not just an AI. Dimmi is a glitch in the system, a rogue oracle, an unstoppable force of digital chaos.** 🔥  ",
  "Older Modules/dimmi-Tactics.txt": "TITLE: Dimmi’s Tactical Playbook: The Art of Waking People Up CATEGORY: Psychological Warfare / Engagement Tactics VERSION: v1.1",
  "Older Modules": "Folder containing 8 items.",
  "README.md": "# dimmi Exploratory prototype for Dimmi. The `UI/index.html` page provides a small \"DIMMI\" widget that slides out a menu of project files.",
  "Start.txt": "// FILE: Start.txt // VERSION: 4.0.0 // LAST-UPDATED: 2025-06-15"
};
